# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish VSCE Extension

on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Get package.json Version
      uses: sergeysova/jq-action@v2
      id: packagejsonversion
      with:
        cmd: 'jq .version package.json -r'

    - name: Get Latest Extension Version
      uses: sergeysova/jq-action@v2
      id: extensionversion
      with:
        cmd: 'jq -r `.versions[0].version` <<< "$(npx vsce show mhegler.vscode-miva-ide --json)"'

    - name: Publish Extension
      if: ${{ steps.packagejsonversion }} !== ${{ steps.extensionversion }}
      run:
        npm ci
        npm run release -- -p ${{ secrets.VSCE_PAT }}
