# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: VSCE Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check version
      id: check
      uses: EndBug/version-check@v2
      with:
        diff-search: true
    - name: Set up node
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm ci
    - name: Publish
      if: steps.check.outputs.changed == 'true'
      run: npm run release -- -p ${{ secrets.VSCE_PAT }}
    - name: Pack
      if: steps.check.outputs.changed == 'true'
      run: npm run pack
    - name: Get Package Information
      if: steps.check.outputs.changed == 'true'
      id: package
      uses: codex-team/action-nodejs-package-info@v1.1
    - name: Create release
      if: steps.check.outputs.changed == 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/${{ steps.package.outputs.name }}-${{ steps.check.outputs.version }}.vsix
        tag_name: v${{ steps.check.outputs.version }}
        make_latest: true
        generate_release_notes: true